version: '2'

services:
  pma:
    image: "phpmyadmin/phpmyadmin"
    environment:
      - PMA_HOSTS=node1db,node2db
      - PMA_USER=dev
      - PMA_PASSWORD=password
    depends_on:
      - node1db
      - node2db
    ports:
      - 5000:80

  node1db:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=dev
      - MYSQL_DATABASE=database
      - MYSQL_PASSWORD=password


  node1:
    tty: true
    build: .
    environment:
      - DB_HOST=node1db
      - DB_USERNAME=dev
      - DB_DATABASE=database
      - DB_PASSWORD=password
      - APPLICATION=node
    depends_on:
      - node1db
    ports:
      - 5001:80
    volumes:
      - ./:/app

  node2db:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=dev
      - MYSQL_DATABASE=database
      - MYSQL_PASSWORD=password

  node2:
    tty: true
    build: .
    environment:
      - DB_HOST=node2db
      - DB_USERNAME=dev
      - DB_DATABASE=database
      - DB_PASSWORD=password
      - APPLICATION=node
    depends_on:
      - node2db
    ports:
      - 5002:80
    volumes:
      - ./:/app


  wallet:
    tty: true
    build: .
    environment:
      - APPLICATION=wallet
      - NODE_HOSTS=node1,node2
    ports:
      - 5003:80
    volumes:
      - ./:/app


  explorer:
    tty: true
    build: .
    environment:
      - APPLICATION=explorer
      - NODE_HOSTS=node1,node2
    ports:
      - 5004:80
    volumes:
      - ./:/app


  miner1.1:
    #restart: always
    tty: true
    build: .
    environment:
      - NODE_HOST=node1
    command: node node/miner.js
    depends_on:
      - node1
    volumes:
      - ./:/app

  miner1.2:
    #restart: always
    tty: true
    build: .
    environment:
      - NODE_HOST=node1
    command: node node/miner.js
    depends_on:
      - node1
    volumes:
      - ./:/app


  miner2.1:
    #restart: always
    tty: true
    build: .
    environment:
      - NODE_HOST=node2
    command: node node/miner.js
    depends_on:
      - node2
    volumes:
      - ./:/app

  miner2.2:
    #restart: always
    tty: true
    build: .
    environment:
      - NODE_HOST=node2
    command: node node/miner.js
    depends_on:
      - node2
    volumes:
      - ./:/app
