version: '2'

services:
  pma:
    image: "phpmyadmin/phpmyadmin"
    environment:
      - PMA_HOSTS=node1db,node2db
      - PMA_USER=dev
      - PMA_PASSWORD=password
    depends_on:
      - node1db
      - node2db
    ports:
      - 5000:80

  node1db:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=dev
      - MYSQL_DATABASE=database
      - MYSQL_PASSWORD=password
    ports:
      - 6000:3306


  node1:
    tty: true
    build: .
    environment:
      - DB_HOST=node1db
      - APPLICATION=node
      - NODE_HOST=node1

      - XDEBUG_CONFIG="idekey=PHPSTORM"
    depends_on:
      - node1db
    ports:
      - 5001:80
    volumes:
      - ./:/app

  node2db:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=dev
      - MYSQL_DATABASE=database
      - MYSQL_PASSWORD=password
    ports:
      - 6001:3306

  node2:
    tty: true
    build: .
    environment:
      - DB_HOST=node2db
      - APPLICATION=node
      - NODE_HOST=node2
      - NODE_PEERS=node1

      - XDEBUG_CONFIG="idekey=PHPSTORM"

    depends_on:
      - node2db
      - node1
    ports:
      - 5002:80
    volumes:
      - ./:/app


  wallet:
    tty: true
    build: .
    environment:
      - APPLICATION=wallet
      - NODE_HOSTS=node1:5001,node2:5002
    ports:
      - 5003:80
    volumes:
      - ./:/app


  explorer:
    tty: true
    build: .
    environment:
      - APPLICATION=explorer
      - NODE_HOSTS=node1:5001,node2:5002 #if the browser needs to communicate
      #- NODE_HOSTS=node1,node2 #if the BE needs to comminicate
    ports:
      - 5004:80
    volumes:
      - ./:/app

  faucet:
    tty: true
    build: .
    environment:
      - APPLICATION=faucet
      - NODE_HOSTS=node1,node2
      - PRIVATE_KEY=0f9d3070204642bc8eb07b00a99ef38eebfec965733a3f70548ce99484fdfd99
    ports:
      - 5005:80
    volumes:
      - ./:/app


  miner1.1:
    restart: always
    tty: true
    build: .
    environment:
      - NODE_HOST=node1
      - ADDRESS=be9c053812ca0cf8ae40aab3047f1b17e586765d
    command: node nodejs/miner.js
    depends_on:
      - node1
    volumes:
      - ./:/app

  miner1.2:
    restart: always
    tty: true
    build: .
    environment:
      - NODE_HOST=node1
      - ADDRESS=c06e8b1d745f50658be0a6e4bd6b01c94878a923
    command: node nodejs/miner.js
    depends_on:
      - node1
    volumes:
      - ./:/app


  miner2.1:
    restart: always
    tty: true
    build: .
    environment:
      - NODE_HOST=node2
      - ADDRESS=9a0bc19436ff653a7c631edc82451a684bccbbb2
    command: node nodejs/miner.js
    depends_on:
      - node2
    volumes:
      - ./:/app

  miner2.2:
    restart: always
    tty: true
    build: .
    environment:
      - NODE_HOST=node2
      - ADDRESS=b379a0f6378b612a46a346e8136ba3b9fb324218
    command: node nodejs/miner.js
    depends_on:
      - node2
    volumes:
      - ./:/app
