version: '2'

services:
  pma:
    image: "phpmyadmin/phpmyadmin"
    environment:
      - PMA_HOSTS=node1db,node2db,faucet1db,faucet2db
      - PMA_USER=dev
      - PMA_DATABASE=database
      - PMA_PASSWORD=password
    depends_on:
      - node1db
      - node2db
      - faucet1db
      - faucet2db
    ports:
      - 5000:80

  node1db:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=dev
      - MYSQL_DATABASE=database
      - MYSQL_PASSWORD=password
    ports:
      - 6000:3306


  node1:
    tty: true
    build: .
    environment:
      - DB_HOST=node1db
      - APPLICATION=node
      - NODE_HOST=node1
      - NODE_PEERS=node2
      - XDEBUG_CONFIG="idekey=PHPSTORM"
    depends_on:
      - node1db
    ports:
      - 5001:80
    volumes:
      - ./:/app

  node2db:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=dev
      - MYSQL_DATABASE=database
      - MYSQL_PASSWORD=password
    ports:
      - 6001:3306

  node2:
    tty: true
    build: .
    environment:
      - DB_HOST=node2db
      - APPLICATION=node
      - NODE_HOST=node2
      - NODE_PEERS=node1

      - XDEBUG_CONFIG="idekey=PHPSTORM"

    depends_on:
      - node2db
      - node1
    ports:
      - 5002:80
    volumes:
      - ./:/app


  wallet:
    tty: true
    build: .
    environment:
      - APPLICATION=wallet
      - NODE_HOSTS=node1:5001,node2:5002
    ports:
      - 5003:80
    volumes:
      - ./:/app


  explorer:
    tty: true
    build: .
    environment:
      - APPLICATION=explorer
      - NODE_HOSTS=node1:5001,node2:5002 #the brawser needs to contact on the external port
    ports:
      - 5004:80
    volumes:
      - ./:/app

  faucet1:
    tty: true
    build: .
    restart: always
    environment:
      - APPLICATION=faucet
      - NODE_HOSTS=node1,node2
      - DB_HOST=faucet1db
      - PRIVATE_KEY=0f9d3070204642bc8eb07b00a99ef38eebfec965733a3f70548ce99484fdfd99
    depends_on:
      - faucet1db
    ports:
      - 5005:80
    volumes:
      - ./:/app

  faucet1_cron:
    tty: true
    build: .
    restart: always
    environment:
      - APPLICATION=faucet
      - NODE_HOSTS=node1,node2
      - DB_HOST=faucet1db
      - PRIVATE_KEY=0f9d3070204642bc8eb07b00a99ef38eebfec965733a3f70548ce99484fdfd99
    depends_on:
      - faucet1db
    command: /root/cron.sh
    volumes:
      - ./:/app


  faucet1db:
    image: 'mariadb:latest'
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=dev
      - MYSQL_DATABASE=database
      - MYSQL_PASSWORD=password
    ports:
      - 6002:3306

  faucet2:
    tty: true
    build: .
    restart: always
    environment:
      - APPLICATION=faucet
      - NODE_HOSTS=node1,node2
      - DB_HOST=faucet2db
      - PRIVATE_KEY=e5fcb644cb5ff2a34d8d479b2fc775c6e4f242ebd8f4eb146bf3985d968c67a5
    depends_on:
      - faucet2db
    ports:
      - 5006:80
    volumes:
      - ./:/app


  faucet2_cron:
    tty: true
    build: .
    restart: always
    environment:
      - APPLICATION=faucet
      - NODE_HOSTS=node1,node2
      - DB_HOST=faucet2db
      - PRIVATE_KEY=e5fcb644cb5ff2a34d8d479b2fc775c6e4f242ebd8f4eb146bf3985d968c67a5
    depends_on:
      - faucet2db
    command: /root/cron.sh
    volumes:
      - ./:/app

  faucet2db:
    image: 'mariadb:latest'
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=dev
      - MYSQL_DATABASE=database
      - MYSQL_PASSWORD=password
    ports:
      - 6003:3306

  miner1:
    restart: always
    tty: true
    build: .
    environment:
      - NODE_HOST=node1
      - ADDRESS=be9c053812ca0cf8ae40aab3047f1b17e586765d
    command: node nodejs/miner.js
    depends_on:
      - node1
    volumes:
      - ./:/app


  miner2:
    restart: always
    tty: true
    build: .
    environment:
      - NODE_HOST=node2
      - ADDRESS=c06e8b1d745f50658be0a6e4bd6b01c94878a923
    command: node nodejs/miner.js
    depends_on:
      - node2
    volumes:
      - ./:/app
