version: '2'

services:
  pma:
    image: "phpmyadmin/phpmyadmin"
    environment:
      - PMA_HOSTS=node1db,node2db
      - PMA_USER=dev
      - PMA_PASSWORD=password
    depends_on:
      - node1db
      - node2db
    ports:
      - 5000:80

  node1db:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=dev
      - MYSQL_DATABASE=database
      - MYSQL_PASSWORD=password


  node1:
    tty: true
    build: .
    labels:
      kompose.service.type: nodeport
    environment:
      - DB_HOST=node1db
      - DB_USERNAME=dev
      - DB_DATABASE=database
      - DB_PASSWORD=password
    depends_on:
      - node1db
    ports:
      - 5001:5000
    volumes:
      - ./:/app

  node2db:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=dev
      - MYSQL_DATABASE=database
      - MYSQL_PASSWORD=password

  node2:
    tty: true
    build: .
    labels:
      kompose.service.type: nodeport
    environment:
      - DB_HOST=node2db
      - DB_USERNAME=dev
      - DB_DATABASE=database
      - DB_PASSWORD=password
    depends_on:
      - node2db
    ports:
      - 5002:5000
    volumes:
      - ./:/app
